### ISSUE TITLE
N pair loss, #class and #sample per class configuration in Deep Fashion In-shop Retrieval Evaluation

### ISSUE THREAD

**Issue by beshining** [ahmdtaha/tf_retrieval_baseline#1]
As stated in table 1,  #class=2 and #sample per class=30 for N pair loss. However, should it be #class=30 and #sample per class=2?

**Comment by ahmdtaha** [comment]
You are correct. I just fixed this typo
Thanks

**Comment by beshining** [comment]
> You are correct. I just fixed this typo
> Thanks

I should also fix my typo in my question 😁
